### ISSUE TITLE
Installation issue windows

### ISSUE THREAD

**Issue by fearghalodonncha** [IBM/lale#552]
A colleague of mine is having issues getting started with Lale on Windows. Installation seems to progress successfully using the `pip install lale[full]` instructions.

The issue is with importing lale libraries. Specifically the command 
`from lale.lib.lale import NoOp, Hyperopt` generates an error (screenshot attached). 

![image](https://user-images.githubusercontent.com/6987323/102241933-6eaffd80-3ef1-11eb-87f3-f79a72f23a02.png)

This is using Windows 10 & Python 3.8.3.

Any suggestions?

**Comment by hirzel** [comment]
Thanks for reporting this. I'm looking into it.

**Comment by hirzel** [comment]
This issue was caused by a missing exception handler, which I now added here: https://github.com/IBM/lale/blob/9f03482ee5ccf65a59c18453bef3174eef420718/lale/helpers.py#L55-L58

Note that the issue only manifests with Python 3.8, and we currently only test Lale with Python 3.6 and 3.7. Also, we routinely use Lale using WSL and a Python virtual environment, but not with Conda.
