### ISSUE TITLE
replace BaselineClassifier/Regressor by DummyClassifier/Regressor

### ISSUE THREAD

**Issue by hirzel** [IBM/lale#618]
Our `lale.lib.lale` package has a [BaselineClassifier](https://github.com/IBM/lale/blob/master/lale/lib/lale/baseline_classifier.py) that simply predicts the majority class. Scikit-learn has a [DummyClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html) that does the same, with a few additional useful configuration options. We should add the DummyClassifier to our `lale.lib.sklearn` package, and eliminate the BaselineClassifier, since it is redundant. Similarly, we should also replace `lale.lib.lale.`[BaselineRegressor](https://github.com/IBM/lale/blob/master/lale/lib/lale/baseline_regressor.py) by scikit-learn's [DummyRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyRegressor.html).

**Comment by tanmaygaikwad** [comment]
Thanks @hirzel for reporting the issue. I'll be working on it and assigning it to myself, starting with https://github.com/IBM/lale/blob/c8ec39b5a9118de89db46c8d2dffb62fb57d1d71/CONTRIBUTING.md

**Comment by hirzel** [comment]
Sounds great :) looking forward to your PR!

**Comment by tanmaygaikwad** [comment]
Hi @hirzel Is there any way either we can connect or I can connect with any existing member from lale team to assist me creating PR.
I have added `DummyClassifier` into `lale.lib.sklearn` but many pre-commit checks are failing which is not allowing me to commit and raise a PR.

Failing pre-comiit checks are not because of my codechange but even checking out master and empty-commit shows these check failures.

**Comment by shinnar** [comment]
Hi @tanmaygaikwad I am happy to assist.  A few notes:

- there were some pre-commit errors recently due to changes in the linters. I just pushed a fix to master.
- what version of python are you using?  I believe that we currently test/support python 3.6 and python 3.7.  I am not sure if our linting currently works on python 3.8 or python 3.9.
- it also looks like you may want to import some more dependencies, such as autoai_libs.  `pip install '.[full]'` should install them.
- Please read the comments I have left on the PR.
- I think we should move further interactions to the PR (unless they are more general design question about the issue)

Thanks for working on this issue!

**Comment by shinnar** [comment]
Closed by #644 .
